services:
  postgres:
    container_name: cold-potato
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agribus-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 3

  influxdb:
    container_name: hot-potato
    image: influxdb:3-core
    restart: unless-stopped
    environment:
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    ports:
      - "8181:8181"
    volumes:
      - influxdb_data:/var/lib/influxdb3
    healthcheck:
      test: [ "CMD-SHELL", "curl -f -H 'Authorization: Bearer ${INFLUXDB_TOKEN}' http://localhost:8181/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - agribus-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: agribus-cold-potato-data
  influxdb_data:
    name: agribus-hot-potato-data

networks:
  agribus-network:
    name: agribus-network
    driver: bridge