// <auto-generated />
using System;
using Agribus.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agribus.Postgres.Migrations
{
    [DbContext(typeof(AgribusDbContext))]
    [Migration("20250710162501_SensorTableMigration")]
    partial class SensorTableMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agribus.Core.Domain.AggregatesModels.SensorAggregates.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SensorModel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sensor_model");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source_address");

                    b.HasKey("Id")
                        .HasName("pk_sensor");

                    b.ToTable("sensor", null, t =>
                        {
                            t.HasComment("Sensors table stores information about sensors used in the system.");

                            t.HasCheckConstraint("CK_Sensor_Model_IsValid", "sensor_model IN ('RuuviTag', 'RuuviTagPro', 'Unknown')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
