proxy:
  container_name: proxy
  image: traefik:v2.7
  restart: always
  command:
    - "--global.sendAnonymousUsage=false"
    - "--providers.docker"
    - "--providers.docker.exposedByDefault=false"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge=true"
    - "--certificatesresolvers.tmhttpchallenge.acme.httpchallenge.entrypoint=web"
    - "--certificatesresolvers.tmhttpchallenge.acme.email=${LETSENCRYPT_EMAIL}"
    - "--certificatesresolvers.tmhttpchallenge.acme.storage=/etc/acme/acme.json"
  ports:
    - "80:80"
    - "443:443"
  networks:
    - proxy
  volumes:
    - ./acme/:/etc/acme/
    - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  reverse-proxy:
    name: reverse-proxy
    external: true
