FROM node:22-alpine as development

WORKDIR /app

RUN npm install -g pnpm@latest
# Install Angular CLI globally
RUN npm install -g @angular/cli@20.0.3

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps/lychee_client ./apps/lychee_client

RUN pnpm install

EXPOSE 4200

ENV NODE_ENV=development

WORKDIR /app
CMD ["pnpm", "--filter", "lychee-client", "dev", "--poll", "500", "--host", "0.0.0.0"]
